# Generated by Django 4.2.6 on 2023-12-13 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_addjob_model_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjob_model',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='addjob_model',
            name='job_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='addjob_model',
            name='Description',
            field=models.TextField(max_length=100),
        ),
    ]
