# Generated by Django 5.0 on 2023-12-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_addjob_model_create_at_addjob_model_job_creator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('present_address', models.TextField()),
                ('permanent_address', models.TextField()),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('previous_job_title', models.CharField(max_length=255)),
                ('experience', models.CharField(choices=[('none', 'None'), ('1', '1 year'), ('2', '2 years'), ('3', '3 years'), ('4', '4 years'), ('5', '5 years or more')], max_length=10)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('edu_qualification', models.ManyToManyField(to='myapp.educationalqualification')),
            ],
        ),
    ]
