# Generated by Django 5.0 on 2023-12-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_educationalqualification_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjob_model',
            name='Company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjob_model',
            name='Description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='addjob_model',
            name='Location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
