# Generated by Django 5.0 on 2023-12-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_addjob_model_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalqualification',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
