# Generated by Django 5.0 on 2024-01-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_userprofile_edu_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
