# Generated by Django 5.0 on 2024-01-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_jobseekerprofile_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('portfolio_link', models.URLField(blank=True, help_text='Portfolio Link', null=True)),
                ('previous_job', models.CharField(blank=True, help_text='Previous Job', max_length=255, null=True)),
                ('job_experience', models.CharField(blank=True, help_text='Job Experience', max_length=255, null=True)),
                ('resume', models.FileField(blank=True, help_text='Upload Resume (PDF, DOC, DOCX)', null=True, upload_to='resumes/')),
                ('skills', models.TextField(blank=True, help_text='Skills', null=True)),
                ('signature', models.ImageField(blank=True, help_text='Upload Signature (PNG, JPG, JPEG)', null=True, upload_to='signatures/')),
                ('cover_letter', models.TextField(blank=True, help_text='Cover Letter', null=True)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, help_text='Expected Salary', max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='permanent_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='present_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
