# Generated by Django 5.0 on 2024-01-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_jobseekerprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom_user',
            old_name='display_name',
            new_name='fullname',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='fname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='lname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
