# Generated by Django 5.0 on 2024-01-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_display_name_custom_user_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='companyname',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
