# Generated by Django 5.0 on 2024-01-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_recruiterprofile_companyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload Resume (PDF, DOC, DOCX)', null=True, upload_to='media/resumes'),
        ),
    ]
