# Generated by Django 5.0 on 2024-01-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_userprofile_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
