# Generated by Django 5.0 on 2024-01-10 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_jobseekerprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Recruiterprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
