# Generated by Django 5.0 on 2024-01-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_recruiterprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='Cover Letter', null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='expected_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected Salary', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='job_experience',
            field=models.CharField(blank=True, help_text='Job Experience', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='portfolio_link',
            field=models.URLField(blank=True, help_text='Portfolio Link', null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='previous_job',
            field=models.CharField(blank=True, help_text='Previous Job', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload Resume (PDF, DOC, DOCX)', null=True, upload_to='media/resumes'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='signature',
            field=models.ImageField(blank=True, help_text='Upload Signature (PNG, JPG, JPEG)', null=True, upload_to='signatures/'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Skills', null=True),
        ),
    ]
