# Generated by Django 4.2.6 on 2024-02-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_jobseekerprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjob_model',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
