# Generated by Django 5.0 on 2024-03-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_job_apply_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
