# Generated by Django 5.0 on 2024-03-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_jobseekerprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.CharField(blank=True, choices=[('PYTHON', 'Python'), ('JAVA', 'Java'), ('PHP', 'php')], max_length=100, null=True),
        ),
    ]
