# Generated by Django 4.2.1 on 2024-03-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_jobseekerprofile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjob_model',
            name='required_skills',
            field=models.CharField(blank=True, choices=[('PYTHON', 'Python'), ('JAVA', 'Java'), ('PHP', 'php')], max_length=255, null=True),
        ),
    ]
