# Generated by Django 4.2.1 on 2024-03-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_addjob_model_required_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addjob_model',
            name='update_at',
        ),
    ]
