# Generated by Django 4.2.1 on 2024-03-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_addjob_model_update_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_apply_model',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='job_apply_model',
            name='job_experience',
        ),
        migrations.RemoveField(
            model_name='job_apply_model',
            name='portfolio_link',
        ),
        migrations.RemoveField(
            model_name='job_apply_model',
            name='previous_job',
        ),
        migrations.RemoveField(
            model_name='job_apply_model',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='job_experience',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='portfolio_link',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='previous_job',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='signature',
        ),
        migrations.AddField(
            model_name='addjob_model',
            name='catagory',
            field=models.CharField(blank=True, choices=[('FULL-TIME', 'Full-Time'), ('PART-Time', 'Part-Time')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addjob_model',
            name='number_of_openings',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected Salary', max_digits=10, null=True),
        ),
    ]
